server:
  port: 8088
spring:
  main:
    banner-mode: 'off'
logging:
  level:
    com.netflix.eureka: 'OFF'
    com.netflix.discovery: 'OFF'

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/

#cloud-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9000,localhost:9001
#    ServerListRefreshInterval: 15000